{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='machine', url='', help='"Machine is the Schema for the machines API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Machine', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'bmc.tinkerbell.org/v1alpha1',
    kind: 'Machine',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"MachineSpec defines desired machine state."'),
  spec: {
    '#connection':: d.obj(help='"Connection contains connection data for a Baseboard Management Controller."'),
    connection: {
      '#authSecretRef':: d.obj(help='"AuthSecretRef is the SecretReference that contains authentication information of the Machine.\\nThe Secret must contain username and password keys. This is optional as it is not required when using\\nthe RPC provider."'),
      authSecretRef: {
        '#withName':: d.fn(help='"name is unique within a namespace to reference a secret resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { connection+: { authSecretRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"namespace defines the space within which the secret name must be unique."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { connection+: { authSecretRef+: { namespace: namespace } } } },
      },
      '#providerOptions':: d.obj(help='"ProviderOptions contains provider specific options."'),
      providerOptions: {
        '#intelAMT':: d.obj(help='"IntelAMT contains the options to customize the IntelAMT provider."'),
        intelAMT: {
          '#withHostScheme':: d.fn(help='"HostScheme determines whether to use http or https for intelAMT calls."', args=[d.arg(name='hostScheme', type=d.T.string)]),
          withHostScheme(hostScheme): { spec+: { connection+: { providerOptions+: { intelAMT+: { hostScheme: hostScheme } } } } },
          '#withPort':: d.fn(help='"Port that intelAMT will use for calls."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { spec+: { connection+: { providerOptions+: { intelAMT+: { port: port } } } } },
        },
        '#ipmitool':: d.obj(help='"IPMITOOL contains the options to customize the Ipmitool provider."'),
        ipmitool: {
          '#withCipherSuite':: d.fn(help='"CipherSuite that ipmitool will use for calls."', args=[d.arg(name='cipherSuite', type=d.T.string)]),
          withCipherSuite(cipherSuite): { spec+: { connection+: { providerOptions+: { ipmitool+: { cipherSuite: cipherSuite } } } } },
          '#withPort':: d.fn(help='"Port that ipmitool will use for calls."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { spec+: { connection+: { providerOptions+: { ipmitool+: { port: port } } } } },
        },
        '#redfish':: d.obj(help='"Redfish contains the options to customize the Redfish provider."'),
        redfish: {
          '#withPort':: d.fn(help='"Port that redfish will use for calls."', args=[d.arg(name='port', type=d.T.integer)]),
          withPort(port): { spec+: { connection+: { providerOptions+: { redfish+: { port: port } } } } },
          '#withSystemName':: d.fn(help='"SystemName is the name of the system to use for redfish calls.\\nWith redfish implementations that manage multiple systems via a single endpoint, this allows for specifying the system to manage."', args=[d.arg(name='systemName', type=d.T.string)]),
          withSystemName(systemName): { spec+: { connection+: { providerOptions+: { redfish+: { systemName: systemName } } } } },
          '#withUseBasicAuth':: d.fn(help='"UseBasicAuth for redfish calls. The default is false which means token based auth is used."', args=[d.arg(name='useBasicAuth', type=d.T.boolean)]),
          withUseBasicAuth(useBasicAuth): { spec+: { connection+: { providerOptions+: { redfish+: { useBasicAuth: useBasicAuth } } } } },
        },
        '#rpc':: d.obj(help='"RPC contains the options to customize the RPC provider."'),
        rpc: {
          '#experimental':: d.obj(help='"Experimental options."'),
          experimental: {
            '#withCustomRequestPayload':: d.fn(help='"CustomRequestPayload must be in json."', args=[d.arg(name='customRequestPayload', type=d.T.string)]),
            withCustomRequestPayload(customRequestPayload): { spec+: { connection+: { providerOptions+: { rpc+: { experimental+: { customRequestPayload: customRequestPayload } } } } } },
            '#withDotPath':: d.fn(help='"DotPath is the path to the json object where the bmclib RequestPayload{} struct will be embedded. For example: object.data.body"', args=[d.arg(name='dotPath', type=d.T.string)]),
            withDotPath(dotPath): { spec+: { connection+: { providerOptions+: { rpc+: { experimental+: { dotPath: dotPath } } } } } },
          },
          '#hmac':: d.obj(help='"HMAC is the options used to create a HMAC signature."'),
          hmac: {
            '#withPrefixSigDisabled':: d.fn(help='"PrefixSigDisabled determines whether the algorithm will be prefixed to the signature. Example: sha256=abc123"', args=[d.arg(name='prefixSigDisabled', type=d.T.boolean)]),
            withPrefixSigDisabled(prefixSigDisabled): { spec+: { connection+: { providerOptions+: { rpc+: { hmac+: { prefixSigDisabled: prefixSigDisabled } } } } } },
            '#withSecrets':: d.fn(help='"Secrets are a map of algorithms to secrets used for signing."', args=[d.arg(name='secrets', type=d.T.object)]),
            withSecrets(secrets): { spec+: { connection+: { providerOptions+: { rpc+: { hmac+: { secrets: secrets } } } } } },
            '#withSecretsMixin':: d.fn(help='"Secrets are a map of algorithms to secrets used for signing."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='secrets', type=d.T.object)]),
            withSecretsMixin(secrets): { spec+: { connection+: { providerOptions+: { rpc+: { hmac+: { secrets+: secrets } } } } } },
          },
          '#request':: d.obj(help='"Request is the options used to create the rpc HTTP request."'),
          request: {
            '#withHttpContentType':: d.fn(help='"HTTPContentType is the content type to use for the rpc request notification."', args=[d.arg(name='httpContentType', type=d.T.string)]),
            withHttpContentType(httpContentType): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { httpContentType: httpContentType } } } } } },
            '#withHttpMethod':: d.fn(help='"HTTPMethod is the HTTP method to use for the rpc request notification."', args=[d.arg(name='httpMethod', type=d.T.string)]),
            withHttpMethod(httpMethod): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { httpMethod: httpMethod } } } } } },
            '#withStaticHeaders':: d.fn(help='"StaticHeaders are predefined headers that will be added to every request."', args=[d.arg(name='staticHeaders', type=d.T.object)]),
            withStaticHeaders(staticHeaders): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { staticHeaders: staticHeaders } } } } } },
            '#withStaticHeadersMixin':: d.fn(help='"StaticHeaders are predefined headers that will be added to every request."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='staticHeaders', type=d.T.object)]),
            withStaticHeadersMixin(staticHeaders): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { staticHeaders+: staticHeaders } } } } } },
            '#withTimestampFormat':: d.fn(help='"TimestampFormat is the time format for the timestamp header."', args=[d.arg(name='timestampFormat', type=d.T.string)]),
            withTimestampFormat(timestampFormat): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { timestampFormat: timestampFormat } } } } } },
            '#withTimestampHeader':: d.fn(help='"TimestampHeader is the header name that should contain the timestamp. Example: X-BMCLIB-Timestamp"', args=[d.arg(name='timestampHeader', type=d.T.string)]),
            withTimestampHeader(timestampHeader): { spec+: { connection+: { providerOptions+: { rpc+: { request+: { timestampHeader: timestampHeader } } } } } },
          },
          '#signature':: d.obj(help='"Signature is the options used for adding an HMAC signature to an HTTP request."'),
          signature: {
            '#withAppendAlgoToHeaderDisabled':: d.fn(help='"AppendAlgoToHeaderDisabled decides whether to append the algorithm to the signature header or not.\\nExample: X-BMCLIB-Signature becomes X-BMCLIB-Signature-256\\nWhen set to true, a header will be added for each algorithm. Example: X-BMCLIB-Signature-256 and X-BMCLIB-Signature-512"', args=[d.arg(name='appendAlgoToHeaderDisabled', type=d.T.boolean)]),
            withAppendAlgoToHeaderDisabled(appendAlgoToHeaderDisabled): { spec+: { connection+: { providerOptions+: { rpc+: { signature+: { appendAlgoToHeaderDisabled: appendAlgoToHeaderDisabled } } } } } },
            '#withHeaderName':: d.fn(help='"HeaderName is the header name that should contain the signature(s). Example: X-BMCLIB-Signature"', args=[d.arg(name='headerName', type=d.T.string)]),
            withHeaderName(headerName): { spec+: { connection+: { providerOptions+: { rpc+: { signature+: { headerName: headerName } } } } } },
            '#withIncludedPayloadHeaders':: d.fn(help='"IncludedPayloadHeaders are headers whose values will be included in the signature payload. Example: X-BMCLIB-My-Custom-Header\\nAll headers will be deduplicated."', args=[d.arg(name='includedPayloadHeaders', type=d.T.array)]),
            withIncludedPayloadHeaders(includedPayloadHeaders): { spec+: { connection+: { providerOptions+: { rpc+: { signature+: { includedPayloadHeaders: if std.isArray(v=includedPayloadHeaders) then includedPayloadHeaders else [includedPayloadHeaders] } } } } } },
            '#withIncludedPayloadHeadersMixin':: d.fn(help='"IncludedPayloadHeaders are headers whose values will be included in the signature payload. Example: X-BMCLIB-My-Custom-Header\\nAll headers will be deduplicated."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includedPayloadHeaders', type=d.T.array)]),
            withIncludedPayloadHeadersMixin(includedPayloadHeaders): { spec+: { connection+: { providerOptions+: { rpc+: { signature+: { includedPayloadHeaders+: if std.isArray(v=includedPayloadHeaders) then includedPayloadHeaders else [includedPayloadHeaders] } } } } } },
          },
          '#withConsumerURL':: d.fn(help='"ConsumerURL is the URL where an rpc consumer/listener is running\\nand to which we will send and receive all notifications."', args=[d.arg(name='consumerURL', type=d.T.string)]),
          withConsumerURL(consumerURL): { spec+: { connection+: { providerOptions+: { rpc+: { consumerURL: consumerURL } } } } },
          '#withLogNotificationsDisabled':: d.fn(help='"LogNotificationsDisabled determines whether responses from rpc consumer/listeners will be logged or not."', args=[d.arg(name='logNotificationsDisabled', type=d.T.boolean)]),
          withLogNotificationsDisabled(logNotificationsDisabled): { spec+: { connection+: { providerOptions+: { rpc+: { logNotificationsDisabled: logNotificationsDisabled } } } } },
        },
        '#withPreferredOrder':: d.fn(help='"PreferredOrder allows customizing the order that BMC providers are called.\\nProviders added to this list will be moved to the front of the default order.\\nProvider names are case insensitive.\\nThe default order is: ipmitool, asrockrack, gofish, intelamt, dell, supermicro, openbmc."', args=[d.arg(name='preferredOrder', type=d.T.array)]),
        withPreferredOrder(preferredOrder): { spec+: { connection+: { providerOptions+: { preferredOrder: if std.isArray(v=preferredOrder) then preferredOrder else [preferredOrder] } } } },
        '#withPreferredOrderMixin':: d.fn(help='"PreferredOrder allows customizing the order that BMC providers are called.\\nProviders added to this list will be moved to the front of the default order.\\nProvider names are case insensitive.\\nThe default order is: ipmitool, asrockrack, gofish, intelamt, dell, supermicro, openbmc."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='preferredOrder', type=d.T.array)]),
        withPreferredOrderMixin(preferredOrder): { spec+: { connection+: { providerOptions+: { preferredOrder+: if std.isArray(v=preferredOrder) then preferredOrder else [preferredOrder] } } } },
      },
      '#withHost':: d.fn(help='"Host is the host IP address or hostname of the Machine."', args=[d.arg(name='host', type=d.T.string)]),
      withHost(host): { spec+: { connection+: { host: host } } },
      '#withInsecureTLS':: d.fn(help='"InsecureTLS specifies trusted TLS connections."', args=[d.arg(name='insecureTLS', type=d.T.boolean)]),
      withInsecureTLS(insecureTLS): { spec+: { connection+: { insecureTLS: insecureTLS } } },
      '#withPort':: d.fn(help='"Port is the port number for connecting with the Machine."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { connection+: { port: port } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
