{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='hardware', url='', help='"Hardware is the Schema for the Hardware API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of Hardware', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'tinkerbell.org/v1alpha1',
    kind: 'Hardware',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"HardwareSpec defines the desired state of Hardware."'),
  spec: {
    '#auto':: d.obj(help='"Auto is the configuration for the automatic capabilities."'),
    auto: {
      '#withEnrollmentEnabled':: d.fn(help='"EnrollmentEnabled enables automatic enrollment of the Hardware.\\nWhen set to true, auto enrollment will create Workflows for this Hardware."', args=[d.arg(name='enrollmentEnabled', type=d.T.boolean)]),
      withEnrollmentEnabled(enrollmentEnabled): { spec+: { auto+: { enrollmentEnabled: enrollmentEnabled } } },
    },
    '#bmcRef':: d.obj(help='"BMCRef contains a relation to a BMC state management type in the same\\nnamespace as the Hardware. This may be used for BMC management by\\norchestrators."'),
    bmcRef: {
      '#withApiGroup':: d.fn(help='"APIGroup is the group for the resource being referenced.\\nIf APIGroup is not specified, the specified Kind must be in the core API group.\\nFor any other third-party types, APIGroup is required."', args=[d.arg(name='apiGroup', type=d.T.string)]),
      withApiGroup(apiGroup): { spec+: { bmcRef+: { apiGroup: apiGroup } } },
      '#withKind':: d.fn(help='"Kind is the type of resource being referenced"', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { bmcRef+: { kind: kind } } },
      '#withName':: d.fn(help='"Name is the name of resource being referenced"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { bmcRef+: { name: name } } },
    },
    '#disks':: d.obj(help=''),
    disks: {
      '#withDevice':: d.fn(help='', args=[d.arg(name='device', type=d.T.string)]),
      withDevice(device): { device: device },
    },
    '#interfaces':: d.obj(help=''),
    interfaces: {
      '#dhcp':: d.obj(help='"DHCP configuration."'),
      dhcp: {
        '#classless_static_routes':: d.obj(help='"ClasslessStaticRoutes defines static routes to be sent via DHCP option 121 (RFC 3442)."'),
        classless_static_routes: {
          '#withDestination_descriptor':: d.fn(help='"DestinationDescriptor is the network address and prefix length.\\nThe format is \\"network/prefixlength\\", e.g., \\"192.168.1.0/24\\" or \\"10.0.0.0/8\\"."', args=[d.arg(name='destination_descriptor', type=d.T.string)]),
          withDestination_descriptor(destination_descriptor): { destination_descriptor: destination_descriptor },
          '#withRouter':: d.fn(help='"Router is the IP address of the router for this route."', args=[d.arg(name='router', type=d.T.string)]),
          withRouter(router): { router: router },
        },
        '#ip':: d.obj(help='"IP configuration."'),
        ip: {
          '#withAddress':: d.fn(help='', args=[d.arg(name='address', type=d.T.string)]),
          withAddress(address): { dhcp+: { ip+: { address: address } } },
          '#withFamily':: d.fn(help='', args=[d.arg(name='family', type=d.T.integer)]),
          withFamily(family): { dhcp+: { ip+: { family: family } } },
          '#withGateway':: d.fn(help='', args=[d.arg(name='gateway', type=d.T.string)]),
          withGateway(gateway): { dhcp+: { ip+: { gateway: gateway } } },
          '#withNetmask':: d.fn(help='', args=[d.arg(name='netmask', type=d.T.string)]),
          withNetmask(netmask): { dhcp+: { ip+: { netmask: netmask } } },
        },
        '#withArch':: d.fn(help='', args=[d.arg(name='arch', type=d.T.string)]),
        withArch(arch): { dhcp+: { arch: arch } },
        '#withBoot_file_name':: d.fn(help='"BootFileName is the boot file name (DHCP option 67).\\nUsed for explicit boot file configuration, required by some network boot clients\\nlike NVIDIA NVOS switches.\\nIf specified, TFTPServerName must also be specified."', args=[d.arg(name='boot_file_name', type=d.T.string)]),
        withBoot_file_name(boot_file_name): { dhcp+: { boot_file_name: boot_file_name } },
        '#withClassless_static_routes':: d.fn(help='"ClasslessStaticRoutes defines static routes to be sent via DHCP option 121 (RFC 3442)."', args=[d.arg(name='classless_static_routes', type=d.T.array)]),
        withClassless_static_routes(classless_static_routes): { dhcp+: { classless_static_routes: if std.isArray(v=classless_static_routes) then classless_static_routes else [classless_static_routes] } },
        '#withClassless_static_routesMixin':: d.fn(help='"ClasslessStaticRoutes defines static routes to be sent via DHCP option 121 (RFC 3442)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='classless_static_routes', type=d.T.array)]),
        withClassless_static_routesMixin(classless_static_routes): { dhcp+: { classless_static_routes+: if std.isArray(v=classless_static_routes) then classless_static_routes else [classless_static_routes] } },
        '#withDomain_name':: d.fn(help='', args=[d.arg(name='domain_name', type=d.T.string)]),
        withDomain_name(domain_name): { dhcp+: { domain_name: domain_name } },
        '#withHostname':: d.fn(help='', args=[d.arg(name='hostname', type=d.T.string)]),
        withHostname(hostname): { dhcp+: { hostname: hostname } },
        '#withIface_name':: d.fn(help='', args=[d.arg(name='iface_name', type=d.T.string)]),
        withIface_name(iface_name): { dhcp+: { iface_name: iface_name } },
        '#withLease_time':: d.fn(help='', args=[d.arg(name='lease_time', type=d.T.integer)]),
        withLease_time(lease_time): { dhcp+: { lease_time: lease_time } },
        '#withMac':: d.fn(help='', args=[d.arg(name='mac', type=d.T.string)]),
        withMac(mac): { dhcp+: { mac: mac } },
        '#withName_servers':: d.fn(help='', args=[d.arg(name='name_servers', type=d.T.array)]),
        withName_servers(name_servers): { dhcp+: { name_servers: if std.isArray(v=name_servers) then name_servers else [name_servers] } },
        '#withName_serversMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='name_servers', type=d.T.array)]),
        withName_serversMixin(name_servers): { dhcp+: { name_servers+: if std.isArray(v=name_servers) then name_servers else [name_servers] } },
        '#withTftp_server_name':: d.fn(help='"TFTPServerName is the TFTP server name or IP address (DHCP option 66).\\nUsed for explicit TFTP server configuration, required by some network boot clients\\nlike NVIDIA NVOS switches.\\nIf specified, BootFileName must also be specified."', args=[d.arg(name='tftp_server_name', type=d.T.string)]),
        withTftp_server_name(tftp_server_name): { dhcp+: { tftp_server_name: tftp_server_name } },
        '#withTime_servers':: d.fn(help='', args=[d.arg(name='time_servers', type=d.T.array)]),
        withTime_servers(time_servers): { dhcp+: { time_servers: if std.isArray(v=time_servers) then time_servers else [time_servers] } },
        '#withTime_serversMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='time_servers', type=d.T.array)]),
        withTime_serversMixin(time_servers): { dhcp+: { time_servers+: if std.isArray(v=time_servers) then time_servers else [time_servers] } },
        '#withUefi':: d.fn(help='', args=[d.arg(name='uefi', type=d.T.boolean)]),
        withUefi(uefi): { dhcp+: { uefi: uefi } },
        '#withVlan_id':: d.fn(help='"validation pattern for VLANDID is a string number between 0-4096"', args=[d.arg(name='vlan_id', type=d.T.string)]),
        withVlan_id(vlan_id): { dhcp+: { vlan_id: vlan_id } },
      },
      '#isoboot':: d.obj(help='"Isoboot configuration."'),
      isoboot: {
        '#withSourceISO':: d.fn(help='"SourceISO is the source url where HookOS, an Operating System Installation Environment (OSIE), ISO lives.\\nIt must be a valid url.URL{} object and must have a url.URL{}.Scheme of HTTP or HTTPS."', args=[d.arg(name='sourceISO', type=d.T.string)]),
        withSourceISO(sourceISO): { isoboot+: { sourceISO: sourceISO } },
      },
      '#netboot':: d.obj(help='"Netboot configuration."'),
      netboot: {
        '#ipxe':: d.obj(help='"IPXE configuration."'),
        ipxe: {
          '#withBinary':: d.fn(help="\"Binary, when defined, overrides Smee's default mapping of architecture to iPXE binary.\\nThe following binary names are supported:\\n- undionly.kpxe\\n- ipxe.efi\\n- snp-arm64.efi\\n- snp-x86_64.efi\\nSee the iPXE Architecture Mapping documentation for more details.\"", args=[d.arg(name='binary', type=d.T.string)]),
          withBinary(binary): { netboot+: { ipxe+: { binary: binary } } },
          '#withContents':: d.fn(help='', args=[d.arg(name='contents', type=d.T.string)]),
          withContents(contents): { netboot+: { ipxe+: { contents: contents } } },
          '#withUrl':: d.fn(help='', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { netboot+: { ipxe+: { url: url } } },
        },
        '#osie':: d.obj(help='"OSIE configuration."'),
        osie: {
          '#withBaseURL':: d.fn(help='', args=[d.arg(name='baseURL', type=d.T.string)]),
          withBaseURL(baseURL): { netboot+: { osie+: { baseURL: baseURL } } },
          '#withInitrd':: d.fn(help='', args=[d.arg(name='initrd', type=d.T.string)]),
          withInitrd(initrd): { netboot+: { osie+: { initrd: initrd } } },
          '#withKernel':: d.fn(help='', args=[d.arg(name='kernel', type=d.T.string)]),
          withKernel(kernel): { netboot+: { osie+: { kernel: kernel } } },
        },
        '#withAllowPXE':: d.fn(help='', args=[d.arg(name='allowPXE', type=d.T.boolean)]),
        withAllowPXE(allowPXE): { netboot+: { allowPXE: allowPXE } },
        '#withAllowWorkflow':: d.fn(help='', args=[d.arg(name='allowWorkflow', type=d.T.boolean)]),
        withAllowWorkflow(allowWorkflow): { netboot+: { allowWorkflow: allowWorkflow } },
      },
      '#withDisableDhcp':: d.fn(help='"DisableDHCP disables DHCP for this interface."', args=[d.arg(name='disableDhcp', type=d.T.boolean)]),
      withDisableDhcp(disableDhcp): { disableDhcp: disableDhcp },
    },
    '#metadata':: d.obj(help=''),
    metadata: {
      '#custom':: d.obj(help=''),
      custom: {
        '#preinstalled_operating_system_version':: d.obj(help=''),
        preinstalled_operating_system_version: {
          '#withDistro':: d.fn(help='', args=[d.arg(name='distro', type=d.T.string)]),
          withDistro(distro): { spec+: { metadata+: { custom+: { preinstalled_operating_system_version+: { distro: distro } } } } },
          '#withImage_tag':: d.fn(help='', args=[d.arg(name='image_tag', type=d.T.string)]),
          withImage_tag(image_tag): { spec+: { metadata+: { custom+: { preinstalled_operating_system_version+: { image_tag: image_tag } } } } },
          '#withOs_slug':: d.fn(help='', args=[d.arg(name='os_slug', type=d.T.string)]),
          withOs_slug(os_slug): { spec+: { metadata+: { custom+: { preinstalled_operating_system_version+: { os_slug: os_slug } } } } },
          '#withSlug':: d.fn(help='', args=[d.arg(name='slug', type=d.T.string)]),
          withSlug(slug): { spec+: { metadata+: { custom+: { preinstalled_operating_system_version+: { slug: slug } } } } },
          '#withVersion':: d.fn(help='', args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { spec+: { metadata+: { custom+: { preinstalled_operating_system_version+: { version: version } } } } },
        },
        '#withPrivate_subnets':: d.fn(help='', args=[d.arg(name='private_subnets', type=d.T.array)]),
        withPrivate_subnets(private_subnets): { spec+: { metadata+: { custom+: { private_subnets: if std.isArray(v=private_subnets) then private_subnets else [private_subnets] } } } },
        '#withPrivate_subnetsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='private_subnets', type=d.T.array)]),
        withPrivate_subnetsMixin(private_subnets): { spec+: { metadata+: { custom+: { private_subnets+: if std.isArray(v=private_subnets) then private_subnets else [private_subnets] } } } },
      },
      '#facility':: d.obj(help=''),
      facility: {
        '#withFacility_code':: d.fn(help='', args=[d.arg(name='facility_code', type=d.T.string)]),
        withFacility_code(facility_code): { spec+: { metadata+: { facility+: { facility_code: facility_code } } } },
        '#withPlan_slug':: d.fn(help='', args=[d.arg(name='plan_slug', type=d.T.string)]),
        withPlan_slug(plan_slug): { spec+: { metadata+: { facility+: { plan_slug: plan_slug } } } },
        '#withPlan_version_slug':: d.fn(help='', args=[d.arg(name='plan_version_slug', type=d.T.string)]),
        withPlan_version_slug(plan_version_slug): { spec+: { metadata+: { facility+: { plan_version_slug: plan_version_slug } } } },
      },
      '#instance':: d.obj(help=''),
      instance: {
        '#ips':: d.obj(help=''),
        ips: {
          '#withAddress':: d.fn(help='', args=[d.arg(name='address', type=d.T.string)]),
          withAddress(address): { address: address },
          '#withFamily':: d.fn(help='', args=[d.arg(name='family', type=d.T.integer)]),
          withFamily(family): { family: family },
          '#withGateway':: d.fn(help='', args=[d.arg(name='gateway', type=d.T.string)]),
          withGateway(gateway): { gateway: gateway },
          '#withManagement':: d.fn(help='', args=[d.arg(name='management', type=d.T.boolean)]),
          withManagement(management): { management: management },
          '#withNetmask':: d.fn(help='', args=[d.arg(name='netmask', type=d.T.string)]),
          withNetmask(netmask): { netmask: netmask },
          '#withPublic':: d.fn(help='', args=[d.arg(name='public', type=d.T.boolean)]),
          withPublic(public): { public: public },
        },
        '#operating_system':: d.obj(help=''),
        operating_system: {
          '#withDistro':: d.fn(help='', args=[d.arg(name='distro', type=d.T.string)]),
          withDistro(distro): { spec+: { metadata+: { instance+: { operating_system+: { distro: distro } } } } },
          '#withImage_tag':: d.fn(help='', args=[d.arg(name='image_tag', type=d.T.string)]),
          withImage_tag(image_tag): { spec+: { metadata+: { instance+: { operating_system+: { image_tag: image_tag } } } } },
          '#withOs_slug':: d.fn(help='', args=[d.arg(name='os_slug', type=d.T.string)]),
          withOs_slug(os_slug): { spec+: { metadata+: { instance+: { operating_system+: { os_slug: os_slug } } } } },
          '#withSlug':: d.fn(help='', args=[d.arg(name='slug', type=d.T.string)]),
          withSlug(slug): { spec+: { metadata+: { instance+: { operating_system+: { slug: slug } } } } },
          '#withVersion':: d.fn(help='', args=[d.arg(name='version', type=d.T.string)]),
          withVersion(version): { spec+: { metadata+: { instance+: { operating_system+: { version: version } } } } },
        },
        '#storage':: d.obj(help=''),
        storage: {
          '#disks':: d.obj(help=''),
          disks: {
            '#partitions':: d.obj(help=''),
            partitions: {
              '#withLabel':: d.fn(help='', args=[d.arg(name='label', type=d.T.string)]),
              withLabel(label): { label: label },
              '#withNumber':: d.fn(help='', args=[d.arg(name='number', type=d.T.integer)]),
              withNumber(number): { number: number },
              '#withSize':: d.fn(help='', args=[d.arg(name='size', type=d.T.integer)]),
              withSize(size): { size: size },
              '#withStart':: d.fn(help='', args=[d.arg(name='start', type=d.T.integer)]),
              withStart(start): { start: start },
              '#withType_guid':: d.fn(help='', args=[d.arg(name='type_guid', type=d.T.string)]),
              withType_guid(type_guid): { type_guid: type_guid },
            },
            '#withDevice':: d.fn(help='', args=[d.arg(name='device', type=d.T.string)]),
            withDevice(device): { device: device },
            '#withPartitions':: d.fn(help='', args=[d.arg(name='partitions', type=d.T.array)]),
            withPartitions(partitions): { partitions: if std.isArray(v=partitions) then partitions else [partitions] },
            '#withPartitionsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='partitions', type=d.T.array)]),
            withPartitionsMixin(partitions): { partitions+: if std.isArray(v=partitions) then partitions else [partitions] },
            '#withWipe_table':: d.fn(help='', args=[d.arg(name='wipe_table', type=d.T.boolean)]),
            withWipe_table(wipe_table): { wipe_table: wipe_table },
          },
          '#filesystems':: d.obj(help=''),
          filesystems: {
            '#mount':: d.obj(help=''),
            mount: {
              '#create':: d.obj(help=''),
              create: {
                '#withForce':: d.fn(help='', args=[d.arg(name='force', type=d.T.boolean)]),
                withForce(force): { mount+: { create+: { force: force } } },
                '#withOptions':: d.fn(help='', args=[d.arg(name='options', type=d.T.array)]),
                withOptions(options): { mount+: { create+: { options: if std.isArray(v=options) then options else [options] } } },
                '#withOptionsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='options', type=d.T.array)]),
                withOptionsMixin(options): { mount+: { create+: { options+: if std.isArray(v=options) then options else [options] } } },
              },
              '#files':: d.obj(help=''),
              files: {
                '#withContents':: d.fn(help='', args=[d.arg(name='contents', type=d.T.string)]),
                withContents(contents): { contents: contents },
                '#withGid':: d.fn(help='', args=[d.arg(name='gid', type=d.T.integer)]),
                withGid(gid): { gid: gid },
                '#withMode':: d.fn(help='', args=[d.arg(name='mode', type=d.T.integer)]),
                withMode(mode): { mode: mode },
                '#withPath':: d.fn(help='', args=[d.arg(name='path', type=d.T.string)]),
                withPath(path): { path: path },
                '#withUid':: d.fn(help='', args=[d.arg(name='uid', type=d.T.integer)]),
                withUid(uid): { uid: uid },
              },
              '#withDevice':: d.fn(help='', args=[d.arg(name='device', type=d.T.string)]),
              withDevice(device): { mount+: { device: device } },
              '#withFiles':: d.fn(help='', args=[d.arg(name='files', type=d.T.array)]),
              withFiles(files): { mount+: { files: if std.isArray(v=files) then files else [files] } },
              '#withFilesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='files', type=d.T.array)]),
              withFilesMixin(files): { mount+: { files+: if std.isArray(v=files) then files else [files] } },
              '#withFormat':: d.fn(help='', args=[d.arg(name='format', type=d.T.string)]),
              withFormat(format): { mount+: { format: format } },
              '#withPoint':: d.fn(help='', args=[d.arg(name='point', type=d.T.string)]),
              withPoint(point): { mount+: { point: point } },
            },
          },
          '#raid':: d.obj(help=''),
          raid: {
            '#withDevices':: d.fn(help='', args=[d.arg(name='devices', type=d.T.array)]),
            withDevices(devices): { devices: if std.isArray(v=devices) then devices else [devices] },
            '#withDevicesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='devices', type=d.T.array)]),
            withDevicesMixin(devices): { devices+: if std.isArray(v=devices) then devices else [devices] },
            '#withLevel':: d.fn(help='', args=[d.arg(name='level', type=d.T.string)]),
            withLevel(level): { level: level },
            '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withSpare':: d.fn(help='', args=[d.arg(name='spare', type=d.T.integer)]),
            withSpare(spare): { spare: spare },
          },
          '#withDisks':: d.fn(help='', args=[d.arg(name='disks', type=d.T.array)]),
          withDisks(disks): { spec+: { metadata+: { instance+: { storage+: { disks: if std.isArray(v=disks) then disks else [disks] } } } } },
          '#withDisksMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='disks', type=d.T.array)]),
          withDisksMixin(disks): { spec+: { metadata+: { instance+: { storage+: { disks+: if std.isArray(v=disks) then disks else [disks] } } } } },
          '#withFilesystems':: d.fn(help='', args=[d.arg(name='filesystems', type=d.T.array)]),
          withFilesystems(filesystems): { spec+: { metadata+: { instance+: { storage+: { filesystems: if std.isArray(v=filesystems) then filesystems else [filesystems] } } } } },
          '#withFilesystemsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='filesystems', type=d.T.array)]),
          withFilesystemsMixin(filesystems): { spec+: { metadata+: { instance+: { storage+: { filesystems+: if std.isArray(v=filesystems) then filesystems else [filesystems] } } } } },
          '#withRaid':: d.fn(help='', args=[d.arg(name='raid', type=d.T.array)]),
          withRaid(raid): { spec+: { metadata+: { instance+: { storage+: { raid: if std.isArray(v=raid) then raid else [raid] } } } } },
          '#withRaidMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='raid', type=d.T.array)]),
          withRaidMixin(raid): { spec+: { metadata+: { instance+: { storage+: { raid+: if std.isArray(v=raid) then raid else [raid] } } } } },
        },
        '#withAllow_pxe':: d.fn(help='', args=[d.arg(name='allow_pxe', type=d.T.boolean)]),
        withAllow_pxe(allow_pxe): { spec+: { metadata+: { instance+: { allow_pxe: allow_pxe } } } },
        '#withAlways_pxe':: d.fn(help='', args=[d.arg(name='always_pxe', type=d.T.boolean)]),
        withAlways_pxe(always_pxe): { spec+: { metadata+: { instance+: { always_pxe: always_pxe } } } },
        '#withCrypted_root_password':: d.fn(help='', args=[d.arg(name='crypted_root_password', type=d.T.string)]),
        withCrypted_root_password(crypted_root_password): { spec+: { metadata+: { instance+: { crypted_root_password: crypted_root_password } } } },
        '#withHostname':: d.fn(help='', args=[d.arg(name='hostname', type=d.T.string)]),
        withHostname(hostname): { spec+: { metadata+: { instance+: { hostname: hostname } } } },
        '#withId':: d.fn(help='', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { spec+: { metadata+: { instance+: { id: id } } } },
        '#withIps':: d.fn(help='', args=[d.arg(name='ips', type=d.T.array)]),
        withIps(ips): { spec+: { metadata+: { instance+: { ips: if std.isArray(v=ips) then ips else [ips] } } } },
        '#withIpsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ips', type=d.T.array)]),
        withIpsMixin(ips): { spec+: { metadata+: { instance+: { ips+: if std.isArray(v=ips) then ips else [ips] } } } },
        '#withIpxe_script_url':: d.fn(help='', args=[d.arg(name='ipxe_script_url', type=d.T.string)]),
        withIpxe_script_url(ipxe_script_url): { spec+: { metadata+: { instance+: { ipxe_script_url: ipxe_script_url } } } },
        '#withNetwork_ready':: d.fn(help='', args=[d.arg(name='network_ready', type=d.T.boolean)]),
        withNetwork_ready(network_ready): { spec+: { metadata+: { instance+: { network_ready: network_ready } } } },
        '#withRescue':: d.fn(help='', args=[d.arg(name='rescue', type=d.T.boolean)]),
        withRescue(rescue): { spec+: { metadata+: { instance+: { rescue: rescue } } } },
        '#withSsh_keys':: d.fn(help='', args=[d.arg(name='ssh_keys', type=d.T.array)]),
        withSsh_keys(ssh_keys): { spec+: { metadata+: { instance+: { ssh_keys: if std.isArray(v=ssh_keys) then ssh_keys else [ssh_keys] } } } },
        '#withSsh_keysMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ssh_keys', type=d.T.array)]),
        withSsh_keysMixin(ssh_keys): { spec+: { metadata+: { instance+: { ssh_keys+: if std.isArray(v=ssh_keys) then ssh_keys else [ssh_keys] } } } },
        '#withState':: d.fn(help='', args=[d.arg(name='state', type=d.T.string)]),
        withState(state): { spec+: { metadata+: { instance+: { state: state } } } },
        '#withTags':: d.fn(help='', args=[d.arg(name='tags', type=d.T.array)]),
        withTags(tags): { spec+: { metadata+: { instance+: { tags: if std.isArray(v=tags) then tags else [tags] } } } },
        '#withTagsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='tags', type=d.T.array)]),
        withTagsMixin(tags): { spec+: { metadata+: { instance+: { tags+: if std.isArray(v=tags) then tags else [tags] } } } },
        '#withUserdata':: d.fn(help='', args=[d.arg(name='userdata', type=d.T.string)]),
        withUserdata(userdata): { spec+: { metadata+: { instance+: { userdata: userdata } } } },
      },
      '#manufacturer':: d.obj(help=''),
      manufacturer: {
        '#withId':: d.fn(help='', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { spec+: { metadata+: { manufacturer+: { id: id } } } },
        '#withSlug':: d.fn(help='', args=[d.arg(name='slug', type=d.T.string)]),
        withSlug(slug): { spec+: { metadata+: { manufacturer+: { slug: slug } } } },
      },
      '#withBonding_mode':: d.fn(help='', args=[d.arg(name='bonding_mode', type=d.T.integer)]),
      withBonding_mode(bonding_mode): { spec+: { metadata+: { bonding_mode: bonding_mode } } },
      '#withState':: d.fn(help='', args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { metadata+: { state: state } } },
    },
    '#withAgentID':: d.fn(help='"AgentID is the unique identifier an Agent uses that is associated with this Hardware.\\nThis is used to identify Hardware during the discovery and enrollment process.\\nIt is typically the MAC address of the primary network interface."', args=[d.arg(name='agentID', type=d.T.string)]),
    withAgentID(agentID): { spec+: { agentID: agentID } },
    '#withDisks':: d.fn(help='', args=[d.arg(name='disks', type=d.T.array)]),
    withDisks(disks): { spec+: { disks: if std.isArray(v=disks) then disks else [disks] } },
    '#withDisksMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='disks', type=d.T.array)]),
    withDisksMixin(disks): { spec+: { disks+: if std.isArray(v=disks) then disks else [disks] } },
    '#withInterfaces':: d.fn(help='', args=[d.arg(name='interfaces', type=d.T.array)]),
    withInterfaces(interfaces): { spec+: { interfaces: if std.isArray(v=interfaces) then interfaces else [interfaces] } },
    '#withInterfacesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='interfaces', type=d.T.array)]),
    withInterfacesMixin(interfaces): { spec+: { interfaces+: if std.isArray(v=interfaces) then interfaces else [interfaces] } },
    '#withReferences':: d.fn(help='"References allows for linking custom resource objects of any kind to this Hardware object.\\nThese are available in Templates for templating. They are referenced by the name of the reference.\\nFor example, given a reference with the name \\"lvm\\", you can access it in a template with .references.lvm."', args=[d.arg(name='references', type=d.T.object)]),
    withReferences(references): { spec+: { references: references } },
    '#withReferencesMixin':: d.fn(help='"References allows for linking custom resource objects of any kind to this Hardware object.\\nThese are available in Templates for templating. They are referenced by the name of the reference.\\nFor example, given a reference with the name \\"lvm\\", you can access it in a template with .references.lvm."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='references', type=d.T.object)]),
    withReferencesMixin(references): { spec+: { references+: references } },
    '#withResources':: d.fn(help='"Resources represents known resources that are available on a machine.\\nResources may be used for scheduling by orchestrators."', args=[d.arg(name='resources', type=d.T.object)]),
    withResources(resources): { spec+: { resources: resources } },
    '#withResourcesMixin':: d.fn(help='"Resources represents known resources that are available on a machine.\\nResources may be used for scheduling by orchestrators."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='resources', type=d.T.object)]),
    withResourcesMixin(resources): { spec+: { resources+: resources } },
    '#withTinkVersion':: d.fn(help='', args=[d.arg(name='tinkVersion', type=d.T.integer)]),
    withTinkVersion(tinkVersion): { spec+: { tinkVersion: tinkVersion } },
    '#withUserData':: d.fn(help="\"UserData is the user data to configure in the hardware's\\nmetadata\"", args=[d.arg(name='userData', type=d.T.string)]),
    withUserData(userData): { spec+: { userData: userData } },
    '#withVendorData':: d.fn(help="\"VendorData is the vendor data to configure in the hardware's\\nmetadata\"", args=[d.arg(name='vendorData', type=d.T.string)]),
    withVendorData(vendorData): { spec+: { vendorData: vendorData } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
